name = "go-usb-ai-competitive-leaderboard"
main = "worker/index.ts"
compatibility_date = "2026-04-14"
workers_dev = true

[[routes]]
pattern = "clawboard.go-usb-ai.io"
custom_domain = true

[assets]
directory = "./dist/client"
binding = "ASSETS"
